"""add printer_id to order_header, change printer_queue type

Revision ID: 2499929c07a6
Revises: 679285b7abf9
Create Date: 2026-05-17 19:02:03.138999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2499929c07a6'
down_revision: Union[str, Sequence[str], None] = '679285b7abf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'model_image',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('order_header', sa.Column('printer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_header', 'printer', ['printer_id'], ['printer_id'])
    op.alter_column('printer', 'printer_queue',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('printer', 'printer_queue',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_constraint(None, 'order_header', type_='foreignkey')
    op.drop_column('order_header', 'printer_id')
    op.alter_column('model', 'model_image',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
