"""add password to users

Revision ID: 332b152d0924
Revises: 130f7356d5c1
Create Date: 2026-05-07 23:43:07.281207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '332b152d0924'
down_revision: Union[str, Sequence[str], None] = '130f7356d5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Filament',
    sa.Column('filament_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=250), nullable=True),
    sa.Column('quantity_in_stock', sa.Float(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('more_wear_and_tear', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('finish_filament', sa.String(length=100), nullable=True),
    sa.Column('filament_price', sa.Float(), nullable=False),
    sa.CheckConstraint('filament_price >= 0', name='filament_price_positive'),
    sa.PrimaryKeyConstraint('filament_id')
    )
    op.create_table('Printer_Type',
    sa.Column('printer_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('printer_name', sa.String(length=100), nullable=True),
    sa.Column('max_size', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('printer_type_id')
    )
    op.create_table('Tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street_address', sa.String(length=250), nullable=False),
    sa.Column('province', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.CheckConstraint("username IS NOT NULL AND username != ''", name='username_not_empty'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Order_Header',
    sa.Column('order_header_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('shipping_price', sa.Float(), nullable=False),
    sa.Column('extra_fee', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('order_tracking_number', sa.String(length=200), nullable=True),
    sa.Column('order_status', sa.Enum('Pending', 'Printing', 'Shipped', 'Completed'), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=500), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_status', sa.Enum('Pending', 'Succeeded', 'Failed'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('order_header_id'),
    sa.UniqueConstraint('order_tracking_number')
    )
    op.create_table('Printer',
    sa.Column('printer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=True),
    sa.Column('printer_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filament_id'], ['Filament.filament_id'], ),
    sa.ForeignKeyConstraint(['printer_type_id'], ['Printer_Type.printer_type_id'], ),
    sa.PrimaryKeyConstraint('printer_id')
    )
    op.create_table('Model',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_length', sa.Float(), nullable=True),
    sa.Column('model_width', sa.Float(), nullable=True),
    sa.Column('model_height', sa.Float(), nullable=True),
    sa.Column('model_description', sa.Text(), nullable=True),
    sa.Column('model_file', sa.String(length=500), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('model_height >= 0', name='height_positive'),
    sa.CheckConstraint('model_length >= 0', name='length_positive'),
    sa.CheckConstraint('model_width >= 0', name='width_positive'),
    sa.ForeignKeyConstraint(['printer_id'], ['Printer.printer_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['Tag.tag_id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('Model_Filament',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['Filament.filament_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['Model.model_id'], ),
    sa.PrimaryKeyConstraint('model_id', 'filament_id')
    )
    op.create_table('Order_Detail',
    sa.Column('order_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('infill_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('order_header_id', sa.Integer(), nullable=True),
    sa.Column('filament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filament_id'], ['Filament.filament_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['Model.model_id'], ),
    sa.ForeignKeyConstraint(['order_header_id'], ['Order_Header.order_header_id'], ),
    sa.PrimaryKeyConstraint('order_detail_id')
    )
    op.drop_table('model_filament')
    op.drop_table('filament')
    op.drop_table('order_detail')
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('phone_number'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('printer_type')
    op.drop_table('printer')
    op.drop_index(op.f('order_tracking_number'), table_name='order_header')
    op.drop_table('order_header')
    op.drop_table('model')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('model_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('model_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model_length', mysql.FLOAT(), nullable=True),
    sa.Column('model_width', mysql.FLOAT(), nullable=True),
    sa.Column('model_height', mysql.FLOAT(), nullable=True),
    sa.Column('model_description', mysql.TEXT(), nullable=True),
    sa.Column('model_file', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('printer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.printer_id'], name=op.f('1')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], name=op.f('2')),
    sa.PrimaryKeyConstraint('model_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_header',
    sa.Column('order_header_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DATE(), nullable=False),
    sa.Column('shipping_price', mysql.FLOAT(), nullable=False),
    sa.Column('extra_fee', mysql.FLOAT(), nullable=True),
    sa.Column('total_price', mysql.FLOAT(), nullable=False),
    sa.Column('order_tracking_number', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('order_status', mysql.ENUM('Pending', 'Printing', 'Shipped', 'Completed'), nullable=False),
    sa.Column('stripe_payment_id', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('payment_status', mysql.ENUM('Pending', 'Succeeded', 'Failed'), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('1')),
    sa.PrimaryKeyConstraint('order_header_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('order_tracking_number'), 'order_header', ['order_tracking_number'], unique=True)
    op.create_table('printer',
    sa.Column('printer_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filament_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('printer_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['filament_id'], ['filament.filament_id'], name=op.f('1')),
    sa.ForeignKeyConstraint(['printer_type_id'], ['printer_type.printer_type_id'], name=op.f('2')),
    sa.PrimaryKeyConstraint('printer_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('printer_type',
    sa.Column('printer_type_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('printer_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('max_size', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('printer_type_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tag',
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tag_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('tag_name'), 'tag', ['tag_name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('street_address', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('province', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.create_table('order_detail',
    sa.Column('order_detail_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('infill_percent', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('scale', mysql.FLOAT(), nullable=True),
    sa.Column('unit_price', mysql.FLOAT(), nullable=True),
    sa.Column('model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order_header_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('filament_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['filament_id'], ['filament.filament_id'], name=op.f('1')),
    sa.ForeignKeyConstraint(['model_id'], ['model.model_id'], name=op.f('2')),
    sa.ForeignKeyConstraint(['order_header_id'], ['order_header.order_header_id'], name=op.f('3')),
    sa.PrimaryKeyConstraint('order_detail_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('filament',
    sa.Column('filament_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('material_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('color_hex', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('quantity_in_stock', mysql.FLOAT(), nullable=True),
    sa.Column('manufacturer', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('more_wear_and_tear', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('finish_filament', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('filament_price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('filament_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('model_filament',
    sa.Column('model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('filament_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filament.filament_id'], name=op.f('1')),
    sa.ForeignKeyConstraint(['model_id'], ['model.model_id'], name=op.f('2')),
    sa.PrimaryKeyConstraint('model_id', 'filament_id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Order_Detail')
    op.drop_table('Model_Filament')
    op.drop_table('Model')
    op.drop_table('Printer')
    op.drop_table('Order_Header')
    op.drop_table('Users')
    op.drop_table('Tag')
    op.drop_table('Printer_Type')
    op.drop_table('Filament')
    # ### end Alembic commands ###
