"""fix price decimals and tag many-to-many

Revision ID: 893e2b64b2a8
Revises: 332b152d0924
Create Date: 2026-05-08 23:50:06.089685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '893e2b64b2a8'
down_revision: Union[str, Sequence[str], None] = '332b152d0924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_tag',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.model_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('model_id', 'tag_id')
    )
    op.alter_column('filament', 'filament_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('2'), 'model', type_='foreignkey')
    op.drop_column('model', 'tag_id')
    op.alter_column('order_detail', 'unit_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('order_header', 'shipping_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('order_header', 'extra_fee',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('order_header', 'total_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_header', 'total_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('order_header', 'extra_fee',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('order_header', 'shipping_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('order_detail', 'unit_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.add_column('model', sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('2'), 'model', 'tag', ['tag_id'], ['tag_id'])
    op.alter_column('filament', 'filament_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.drop_table('model_tag')
    # ### end Alembic commands ###
