"""add filament_printer junction table

Revision ID: d395b5bfb28f
Revises: 2499929c07a6
Create Date: 2026-05-19 17:57:33.526369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd395b5bfb28f'
down_revision: Union[str, Sequence[str], None] = '2499929c07a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filament_printer',
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('filament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filament_id'], ['filament.filament_id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.printer_id'], ),
    sa.PrimaryKeyConstraint('printer_id', 'filament_id')
    )
    op.drop_constraint(op.f('1'), 'printer', type_='foreignkey')
    op.drop_column('printer', 'filament_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('filament_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('1'), 'printer', 'filament', ['filament_id'], ['filament_id'])
    op.drop_table('filament_printer')
    # ### end Alembic commands ###
