name: Trigger unittest
env:
  PYTHONPATH: .
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: './printshop-frontend/package-lock.json'

      - name: Install jest
        run: npm ci
        working-directory: ./printshop-frontend

      - name: Install sqlalchemy
        run: pip install sqlalchemy
        
      - name: Install mysqlclient
        run: pip install mysqlclient

      - name: Run backend tests
        run: python -m unittest discover -s tests

#      - name: Debug - List Files
#        run: ls -R

#      - name: Run frontend tests
#        run: npm test
#        working-directory: ./printshop-frontend