name: Trigger unittest
env:
  PYTHONPATH: .
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install sqlalchemy
        run: pip install sqlalchemy
        
      - name:  Install mysqlclient
        run: pip install mysqlclient

      - name: Run test
        run: python -m unittest discover -s tests

       
